/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sanjeevaniapp.gui;

import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sanjeevaniapp.dao.UserDao;
import sanjeevaniapp.dbutil.DBconnection;
import sanjeevaniapp.pojo.UserPojo;
import sanjeevaniapp.pojo.UserProfile;
import sanjeevaniapp.utilty.PasswordEncryption;

/**
 *
 * @author sumon
 */
public class Log_In_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Log_In_Frame
     */
    private String loginId;
    private String password;
    public Log_In_Frame() {
        initComponents();
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmpId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmpPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jrbtnEmpAdmin = new javax.swing.JRadioButton();
        jrbtnEmpDoctor = new javax.swing.JRadioButton();
        jrbtnEmpReceptionist = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnEmpLogin = new javax.swing.JButton();
        btnEmpQuit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabel2.setText("Sanjeevani Application");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 370, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevaniapp/icons/icons/HomePageBG1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Login ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 130, 30));

        txtEmpId.setBackground(new java.awt.Color(204, 255, 255));
        txtEmpId.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txtEmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 470, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 120, 30));

        txtEmpPassword.setBackground(new java.awt.Color(204, 255, 255));
        txtEmpPassword.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel1.add(txtEmpPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 490, 30));

        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 1000, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("User Type");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 110, 30));

        jrbtnEmpAdmin.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbtnEmpAdmin);
        jrbtnEmpAdmin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbtnEmpAdmin.setText("ADMIN");
        jPanel1.add(jrbtnEmpAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));

        jrbtnEmpDoctor.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbtnEmpDoctor);
        jrbtnEmpDoctor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbtnEmpDoctor.setText("DOCTOR");
        jPanel1.add(jrbtnEmpDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, -1, -1));

        jrbtnEmpReceptionist.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbtnEmpReceptionist);
        jrbtnEmpReceptionist.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbtnEmpReceptionist.setText("RECEPTIONIST");
        jPanel1.add(jrbtnEmpReceptionist, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 520, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 562, 1000, 10));

        btnEmpLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEmpLogin.setText("Login");
        btnEmpLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmpLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 280, -1));

        btnEmpQuit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEmpQuit.setText("Quit");
        btnEmpQuit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpQuitActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmpQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, 280, -1));

        jLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 1060, 240));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpLoginActionPerformed
       boolean isInputValid=validateInputs();
        if(isInputValid==false){
            JOptionPane.showMessageDialog(null,"Please input id and password");
            return;
        }
        String userType=getUserType();
        if(userType==null){
            JOptionPane.showMessageDialog(null,"Please select a user type");
            return;
        }
        try{
           // System.out.println(jrbtnEmpDoctor.getText());
            UserPojo user=new UserPojo();
            user.setUserId(loginId);
            String pwd=new String(PasswordEncryption.getEncryptedPassword(password));
            user.setPassword(pwd);
            user.setUserType(userType);
            String userName=UserDao.validateUser(user);
            if(userName!=null){
                JOptionPane.showMessageDialog(null,"Welcome "+userName,"Login success!",JOptionPane.INFORMATION_MESSAGE);
                UserProfile.setUserName(userName);
                UserProfile.setUserType(userType);
                UserProfile.setUserId(loginId);
                JFrame optionsFrame=null;
                if(userType.equalsIgnoreCase("admin")){
                   optionsFrame=new AdminOptionsFrame();
                 }
                else if(userType.equalsIgnoreCase("receptionist")){
                   optionsFrame=new ReceptionistOptionFrame();
                 }
                else{
                    optionsFrame=new DoctorOptionFrame();
                }
                optionsFrame.setVisible(true);
                this.dispose();
                return;
                
            }
            JOptionPane.showMessageDialog(null,"Invalid credentials!","Login denied!",JOptionPane.ERROR_MESSAGE);
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error In DB"+ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnEmpLoginActionPerformed

    private void btnEmpQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpQuitActionPerformed
        DBconnection.closeConnection();
            System.exit(0);
    }//GEN-LAST:event_btnEmpQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log_In_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log_In_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log_In_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log_In_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log_In_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpLogin;
    private javax.swing.JButton btnEmpQuit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton jrbtnEmpAdmin;
    private javax.swing.JRadioButton jrbtnEmpDoctor;
    private javax.swing.JRadioButton jrbtnEmpReceptionist;
    private javax.swing.JTextField txtEmpId;
    private javax.swing.JPasswordField txtEmpPassword;
    // End of variables declaration//GEN-END:variables

    private boolean validateInputs() {
        loginId=txtEmpId.getText().trim();
        char []pwd=txtEmpPassword.getPassword();
        if(loginId.isEmpty()|| pwd.length==0)
            return false;
        password=new String(pwd);
        return true;
        
    }

  
        private String getUserType() {
        if(jrbtnEmpAdmin.isSelected())
            return jrbtnEmpAdmin.getText();
        else if(jrbtnEmpDoctor.isSelected())
            return jrbtnEmpDoctor.getText();
        else if(jrbtnEmpReceptionist.isSelected())
            return jrbtnEmpReceptionist.getText();
        return null;
    }
    
}
