/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sanjeevaniapp.gui;

import sanjeevaniapp.dbutil.DBconnection;

/**
 *
 * @author sumon
 */
public class ManageReceptionistFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManageReceptionistFrame
     */
    public ManageReceptionistFrame() {
        initComponents();
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblShowName = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnReceptionistAdd = new javax.swing.JButton();
        btnReceptionistUpdate = new javax.swing.JButton();
        btnreceptionistView = new javax.swing.JButton();
        btnReceptionistRemove = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sitka Subheading", 1, 36)); // NOI18N
        jLabel2.setText("Sanjeevani Application");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 410, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevaniapp/icons/icons/HomePageBG1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("        Manage Receptionist");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 50));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hello,");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 30));

        lblShowName.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblShowName.setForeground(new java.awt.Color(255, 255, 255));
        lblShowName.setText("USER-SUMON");
        jPanel4.add(lblShowName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 170, 30));

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 204, 204));
        btnLogout.setText("Logout");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel4.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 120, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 710, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevaniapp/icons/icons/doctor.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 200, 160));

        btnReceptionistAdd.setBackground(new java.awt.Color(0, 204, 204));
        btnReceptionistAdd.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnReceptionistAdd.setText("Add Receptionist");
        btnReceptionistAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReceptionistAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceptionistAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnReceptionistAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 270, 60));

        btnReceptionistUpdate.setBackground(new java.awt.Color(0, 204, 204));
        btnReceptionistUpdate.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnReceptionistUpdate.setText("Update Receptionist");
        btnReceptionistUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReceptionistUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceptionistUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnReceptionistUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 270, 60));

        btnreceptionistView.setBackground(new java.awt.Color(0, 204, 204));
        btnreceptionistView.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnreceptionistView.setText("View Receptionist");
        btnreceptionistView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreceptionistView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreceptionistViewActionPerformed(evt);
            }
        });
        jPanel2.add(btnreceptionistView, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 260, 60));

        btnReceptionistRemove.setBackground(new java.awt.Color(0, 204, 204));
        btnReceptionistRemove.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnReceptionistRemove.setText("Remove Receptionist");
        btnReceptionistRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReceptionistRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceptionistRemoveActionPerformed(evt);
            }
        });
        jPanel2.add(btnReceptionistRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 260, 60));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 153, 153));
        btnBack.setText("Back");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 210, 110, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 1050, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        DBconnection.closeConnection();
        System.exit(0);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnReceptionistAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceptionistAddActionPerformed
                    AddReceptionist optionFrame=new AddReceptionist();
                    optionFrame.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_btnReceptionistAddActionPerformed

    private void btnReceptionistUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceptionistUpdateActionPerformed
                    UpdateReceptionistFrame optionFrame=new UpdateReceptionistFrame();
                    optionFrame.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_btnReceptionistUpdateActionPerformed

    private void btnreceptionistViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreceptionistViewActionPerformed
                  ViewAllReceptionistFrame optionFrame=new ViewAllReceptionistFrame();
                    optionFrame.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_btnreceptionistViewActionPerformed

    private void btnReceptionistRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceptionistRemoveActionPerformed
                     RemoveReceptionistFrame optionFrame=new RemoveReceptionistFrame();
                    optionFrame.setVisible(true);
                    this.dispose();  
    }//GEN-LAST:event_btnReceptionistRemoveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        AdminOptionsFrame optionsFrame=new AdminOptionsFrame();
        optionsFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageReceptionistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageReceptionistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageReceptionistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageReceptionistFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageReceptionistFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReceptionistAdd;
    private javax.swing.JButton btnReceptionistRemove;
    private javax.swing.JButton btnReceptionistUpdate;
    private javax.swing.JButton btnreceptionistView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblShowName;
    // End of variables declaration//GEN-END:variables
}
