/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sanjeevaniapp.gui;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import sanjeevaniapp.dao.AppointmentDao;
import sanjeevaniapp.dao.DoctorDao;
import sanjeevaniapp.dao.PatientDao;
import sanjeevaniapp.dbutil.DBconnection;
import sanjeevaniapp.pojo.AppointmentPojo;
import sanjeevaniapp.pojo.PatientPojo;
import sanjeevaniapp.utilty.OTPSender;
import sanjeevaniapp.utilty.Sender;

/**
 *
 * @author sumon
 */
public class VerifyOtpFrame2 extends javax.swing.JFrame {

    /**
     * Creates new form VerifyOtpFrame2
     */
     private PatientPojo patient;
    public VerifyOtpFrame2() {
        initComponents();
        super.setLocationRelativeTo(null);
    }
    public VerifyOtpFrame2(PatientPojo patient) {
       this();
       txtPatientName.setText(patient.getF_Name()+" "+patient.getL_Name());
       txtPatientNumber.setText(patient.getMobile_no());
       this.patient=patient;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        txtOTP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPatientNumber = new javax.swing.JTextField();
        btnSendOtp = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnBack = new javax.swing.JButton();
        btnVerify = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setText("Sanjeevani Application");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 430, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevaniapp/icons/icons/HomePageBG1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("  Patients Details");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Patient Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 110, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Enter OTP");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 100, 20));

        txtPatientName.setEditable(false);
        txtPatientName.setBackground(new java.awt.Color(204, 255, 255));
        txtPatientName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel2.add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 240, -1));

        txtOTP.setBackground(new java.awt.Color(204, 255, 255));
        txtOTP.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel2.add(txtOTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 410, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Phone no.");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 80, 20));

        txtPatientNumber.setEditable(false);
        txtPatientNumber.setBackground(new java.awt.Color(204, 255, 255));
        txtPatientNumber.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel2.add(txtPatientNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 270, -1));

        btnSendOtp.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSendOtp.setForeground(new java.awt.Color(0, 102, 102));
        btnSendOtp.setText("SEND OTP");
        btnSendOtp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSendOtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendOtpActionPerformed(evt);
            }
        });
        jPanel2.add(btnSendOtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 250, -1));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 168, 930, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 102, 102));
        btnBack.setText("BACK");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 110, -1));

        btnVerify.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnVerify.setForeground(new java.awt.Color(0, 102, 102));
        btnVerify.setText("VERIFY");
        btnVerify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });
        jPanel2.add(btnVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 200, 320, -1));

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 102, 102));
        btnLogout.setText("LOGOUT");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(769, 200, 150, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 950, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendOtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendOtpActionPerformed
        try{
            Sender sender=new OTPSender();
            String potp=String.valueOf(patient.getOTP());
            boolean result=sender.send(patient.getMobile_no(), potp);
            if(!result)
            {
                JOptionPane.showMessageDialog(null,"OTP Sent successfully");
            }else{
                JOptionPane.showMessageDialog(null,"Cannot send the OTP . please check the number!");
            }
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,"Server issue");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSendOtpActionPerformed

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
        if(!isValidOTP()){
            JOptionPane.showMessageDialog(null,"Invalid OTP. try Again!");
            return;
        }
        try
        {
            AppointmentPojo appojo=new AppointmentPojo();
//            appojo.setDate_Time(patient.getDate().toString());
            appojo.setMobile_no(patient.getMobile_no());
            appojo.setOPD(patient.getOPD());
            appojo.setPatient_id(patient.getPatient_id());
            appojo.setPatient_name(txtPatientName.getText().trim());
            appojo.setStatus("REQUEST");

            String docName=DoctorDao.getDoctorNameById(patient.getDoctor_id());
            appojo.setDoctor_Name(docName);
            boolean result1=PatientDao.UpdatePatient(patient);
            boolean result2=AppointmentDao.Updateappoitnment(appojo);
            if(result1 && result2)
            {
                JOptionPane.showMessageDialog(null,"Patient record updated successfully!!");
//                ViewAllPatientFrame viewAll=new ViewAllPatientFrame();
//                this.dispose();
//                viewAll.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(null,"Sorry! could not Update the patient record!");
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error in DB in verifyFrame2:"+ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnVerifyActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        DBconnection.closeConnection();
        System.exit(0);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
      UpdatePatientFrame optionFrame=new UpdatePatientFrame();
      optionFrame.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerifyOtpFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerifyOtpFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerifyOtpFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerifyOtpFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerifyOtpFrame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSendOtp;
    private javax.swing.JButton btnVerify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtOTP;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPatientNumber;
    // End of variables declaration//GEN-END:variables
   private boolean isValidOTP(){
        boolean result =false;
        try{
            int otp=Integer.parseInt(txtOTP.getText().trim());
            if(otp==patient.getOTP())
                result=true;
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Please input digits only!");
            ex.printStackTrace();
        }finally{
            return result;
        }
    }
}
